name: Build & Push Container

on:
  workflow_dispatch:
  push:
    branches:
       - 'main'
    paths-ignore:
      - 'resumes/**'
      - '.github/**'  

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build and push docker image
      run: |
        TIMESTAMP=$(date +%s)
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/jsonresumefull:${TIMESTAMP} -f docker/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/jsonresumefull:${TIMESTAMP}
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/jsonresumefull:latest -f docker/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/jsonresumefull:latest


  
 
