name: Validate Docker Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - 'resumes/**'
      - '.github/**'  

jobs:
  docker_validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build container
      run: |
        TIMESTAMP=$(date +%s)
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/jsonresumefull:${TIMESTAMP} -f docker/Dockerfile .


  
 
